name: test action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug SSH Variables
      run: |
        if [ -z "$secret.SSH_PRIVATE_KEY" ]; then echo "SSH_PRIVATE_KEY is empty"; else echo "SSH_PRIVATE_KEY is set"; fi
        if [ -z "$secret.SSH_HOST" ]; then echo "SSH_HOST is empty"; else echo "SSH_HOST is set"; fi
        if [ -z "$secret.SSH_USER" ]; then echo "SSH_USER is empty"; else echo "SSH_USER is set"; fi


    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$secret.SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "$secret.SSH_HOST" >> ~/.ssh/known_hosts

    - name: Create file on VPS
      run: |
        ssh $secret.SSH_USER@$secret.SSH_HOST "echo 'Este es un archivo creado desde GitHub Actions' > ~/archivo.txt"
